name: Carbon CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.12
      with:
        extensions: 'h,cpp'
